### ISSUE TITLE
单周期RISC-V就过不了

### ISSUE THREAD

**Issue by G23yl** [Yiipu/HUST-HardwareDesign-RISCv#1]
一直是1到24循环，感觉是jal指令实现有问题

**Comment by Yiipu** [comment]
确实有问题, 跳转地址连的是立即数而不是 ALU 结果. 把连线改一下就可以了.
支持跳转的流水线应该没有这个问题

**Comment by G23yl** [comment]
谢谢，我自己发现这个问题改过来了
